apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-cpu-bound-fastapi
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: orchestrated-rollout-portability
spec:
  project: default
  source:
    repoURL: https://campus.cs.le.ac.uk/gitlab/pgt_project/25_26_spring/aks85.git
    targetRevision: main
    path: charts/portable-workload
    helm:
      releaseName: cpu-bound-fastapi
      valueFiles:
        - values.yaml
        - ../../gitops/workloads/cpu-bound-fastapi/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: workload-cpu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
