apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-io-latency-node
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: orchestrated-rollout-portability
spec:
  project: default
  source:
    repoURL: https://github.com/AbdulKhumainiShaik/orchestrator-testing.git
    targetRevision: main
    path: charts/portable-workload
    helm:
      releaseName: io-latency-node
      valueFiles:
        - values.yaml
        - ../../gitops/workloads/io-latency-node/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: workload-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
